### ISSUE TITLE
Add support for Dropdown.Menu?

### ISSUE THREAD

**Issue by tmm1** [felipecarrillo100/react-bootstrap-submenu#2]
Thanks for sharing this project!

I wonder if support for Dropdown.Menu can be added so submenu can be used outside of a navbar.

**Comment by felipecarrillo100** [comment]
It should be possible with some additional coding.  I'm not planning to make changes at the moment as the module currently serves its purpose.  

But the source code is there so feel free to have a look and I hope it can give you some ideas on how to do what you want.

**Comment by felipecarrillo100** [comment]
Not planned. For the moment this is only for Nav bars
