### ISSUE TITLE
Can't get the demo to work..

### ISSUE THREAD

**Issue by rhysmitchell** [felipecarrillo100/react-bootstrap-submenu#6]
I pulled up a simple [CodeSandbox](https://codesandbox.io/s/react-bootstrap-submenu-l90rv?file=/src/App.js) to test this uber handy package out but the exemplar markup doesn't seem to be rendering the `DropDown 1`.

**Comment by felipecarrillo100** [comment]
That doesn't seem related with my code.  If you test you will notice that the standard NavDropdown from the official "react-bootstrap" seems not working either in your codesandbox. My library depends on   NavDropdown  working properly.

I will suggest make your CodeSandbox work with the standard react-bootstrap NavDropdown before importing my library.  Once you get it working you can safely include my library ("react-bootstrap-submenu") and it should work as well.

**Comment by felipecarrillo100** [comment]
This sandbox should work fine.  You may need to resize the window to see the submenus.

https://codesandbox.io/s/react-bootstrap-submenu-hz17d

**Comment by felipecarrillo100** [comment]
Not related to the code of this project.  Probably a miss configuration in is codesandbox
