### ISSUE TITLE
Open & close on hover?

### ISSUE THREAD

**Issue by fwielstra** [felipecarrillo100/react-bootstrap-submenu#7]
At the moment the submenu only opens and closes when clicking on it. However, with elements like this, I find it more natural if they open on hover and close when not focused.

Second, using it as a Dropdown (instead of in a nav) seems to work fine, but the 'open' state seems to be retained when closing the dropdown or when clicking an item outside of the submenu.

**Comment by felipecarrillo100** [comment]
This is not an issue.  The module works as expected. 
This component was never intended to be used with a dropdown.  The instructions are clear. This component is to be used within a NavBar component. 
Closing the issue.
Note: Source code is available. Feel free to fork it and adapt it to our needs. There is a component called react-contexify
that perhaps meets your needs.
