### ISSUE TITLE
I tried using react in nextjs and the following error occurred

### ISSUE THREAD

**Issue by marcosvspimenta** [felipecarrillo100/react-bootstrap-submenu#9]
I tried using react in nextjs and the following error occurred

./node_modules/react-bootstrap-submenu/src/index.css
Global CSS cannot be imported from within node_modules.
Read more: https://nextjs.org/docs/messages/css-npm
Location: node_modules\react-bootstrap-submenu\dist\DropdownSubmenu.js

This error occurred during the build process and can only be dismissed by fixing the error.

**Comment by felipecarrillo100** [comment]
I have answered to same question before. The module expects you support
importing css files in your code. Solve it in your environment or split the
cost import. Read closed issues

**Comment by marcosvspimenta** [comment]
@felipecarrillo100 First, thanks for the answer. I tried using the fork but it didn't work. Look at Nextjs website guidance. "Possible Ways to Fix It
Reach out to the maintainer and ask for them to publish a compiled version of their dependency.

Compiled dependencies do not have references to CSS files, or any other files that require bundler-specific integrations."

Is it possible to do that?

**Comment by felipecarrillo100** [comment]
I created version 2.0.0   where the css styling has been moved to an external file that you will have to add to your project.
